allowBuilds:
<<<<<<< HEAD
  sharp: true
  unrs-resolver: true
=======
  sharp: false
  unrs-resolver: false
>>>>>>> f6f198114c53f29c632f1d548c23dae24c065f16
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
